"""drop redundant contact_messages columns and indexes

Revision ID: 2ef599b5575b
Revises: 0001_baseline
Create Date: 2026-08-30 23:03:17.567953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002_cleanup"
down_revision: Union[str, None] = "0001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_messages_read_timestamp", table_name="contact_messages")
    op.drop_index("idx_messages_timestamp_desc", table_name="contact_messages")
    op.drop_index("ix_contact_messages_email", table_name="contact_messages")
    op.drop_index("ix_contact_messages_name", table_name="contact_messages")
    op.drop_index("ix_contact_messages_read", table_name="contact_messages")
    op.create_index(
        "idx_messages_created_at_desc",
        "contact_messages",
        [sa.text("created_at DESC")],
        unique=False,
    )
    op.drop_column("contact_messages", "read")
    op.drop_column("contact_messages", "timestamp")
    op.drop_column("contact_messages", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contact_messages",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "contact_messages",
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "contact_messages",
        sa.Column(
            "read",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("idx_messages_created_at_desc", table_name="contact_messages")
    op.create_index(
        "ix_contact_messages_read", "contact_messages", ["read"], unique=False
    )
    op.create_index(
        "ix_contact_messages_name", "contact_messages", ["name"], unique=False
    )
    op.create_index(
        "ix_contact_messages_email", "contact_messages", ["email"], unique=False
    )
    op.create_index(
        "idx_messages_timestamp_desc",
        "contact_messages",
        [sa.text("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "idx_messages_read_timestamp",
        "contact_messages",
        ["read", sa.text("timestamp DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
